### PR TITLE
Enhance state.json handling with parallel kubie processes

### LINKED ISSUE #66: Using multiple sessions in parallel can corrupt kubie state.json
Hi there;

New kubie user here. I use iTerm2 and multiple session panes in the same window. Kubie has been a life saver, allowing me to have a pane for each cluster I'm working on and work on them in parallel using iTerm2's Broadcast Input feature. However, I ran into an issue today where I ran `kubie ns foo` in parallel that caused all of the kubie sessions to update the state.json file at the same time, which corrupted it.

The error I received later on when I tried to enter a context in a new terminal window was not super helpful in pointing me to what the underlying problem was either:
```
$ kubie ctx foo
Error: trailing characters at line 1 column 102
```

I was able to find the state.json file and simply delete it, which allowed kubie to continue working for me again.

I think kubie probably needs some sort of file lock or some other mechanism to avoid parallel invocations of kubie from corrupting the state.json file, and I think kubie could provide a little more context around that particular error, perhaps even printing the path to the state.json file it's encountering the error in as well. (I had originally looked for it at `~/.local/share/kubie/state.json`, but on my Mac the state.json was actually in `~/Library/Application Support/kubie/state.json`.

I've been looking for an excuse to learn Rust, so this may be it... but figured I'd start by raising an issue in case someone else is able/wants to look at it before I can get around to learning enough to figure it out and submit a PR.

Cheers,
Ty

### PR DESCRIPTION
**Pull request by TyBrown**
Closes #66 

I took a stab at fixing this... first time doing much of anything in Rust, so feedback is definitely welcome! :)

I was able to reliably reproduce this issue with 3-4 parallel sessions and changing namespaces less than once per second, within about 2 or 3 ops. After applying this patch, I ran 9 parallel sessions, changing namespaces up to 10 times / second, and while I occasionally got empty state files read in, I could not get a corrupted state.json, so I think this is a marked improvement.

### CODE REVIEW

**Comment by sbstp** [comment]
So I look a look at the code, and the only place where we save this file is right after a load, [here](https://github.com/sbstp/kubie/blob/master/src/cmd/namespace.rs#L65). I think using a file lock would solve the problem in its entirety, lock the file, read it, update the data structure, save it, and unlock.

Another alternative could be to use something with built-in concurrent access like SQLite, though that would make the binary a bit bigger.

**Comment by TyBrown** [comment]
@sbstp I implemented the file locking, but still left the atomic file write in place since it was still low overhead in the code. Let me know if you would prefer that I remove it.

File: src/state.rs [hunk 1]
```diff
@@ -30,14 +38,56 @@ pub struct State {
...
+
+        // Acquire the lock
+        let flock = File::create(lock_path())?;
+        flock
+            .lock_exclusive()
+            .with_context(|| format!("Failed to lock state: {}", path))?;
+
+        // Do the work
+        let state = State::read_and_parse()
+            .with_context(|| format!("Could not load state file: {}", KUBIE_STATE_PATH.to_str().unwrap()));
```
Comment (sbstp) [inline src/state.rs]: Can you use Path.display here instead of panicking?

File: src/state.rs [hunk 2]
```diff
@@ -30,14 +38,56 @@ pub struct State {
...
+        let result = match state {
```
Comment (sbstp) [inline src/state.rs]: Instead of doing a match I think you could map over the result returned by `read_and_parse()`, i.e:

```rust
let result = State::read_and_parse()
  .with_context(|| format!("Could not load state file: {}", KUBIE_STATE_PATH.display()))
  .map(func);
```

File: src/state.rs (hunk 1 above)
Comment (TyBrown) [reply src/state.rs]: Good catch! I've cleaned all of those up.

File: src/state.rs (hunk 2 above)
Comment (TyBrown) [reply src/state.rs]: Great suggestion! I ended up using `.and_then()` instead of `.map()` due to the return types mismatching in the function signatures generic of `F`.

Comment (sbstp) [reply src/state.rs]: Yeah there's multiple ways of mapping on errors depending on which type your closure returns.

**Review by sbstp — APPROVED** [review]

**Comment by sbstp** [comment]
I'll just test this out manually and make sure everything is good on my machine and then merge.

**Comment by sbstp** [comment]
Thanks! Looks good.

**Comment by sbstp** [comment]
Out in 0.13.3

**Comment by sbstp** [comment]
We got a bug report in #69, seems like we forgot something

File: src/state.rs [hunk 3]
```diff
@@ -30,14 +38,52 @@ pub struct State {
...
+            state.save()?;
+            Ok(())
+        })
+    }
+
+    fn access<R, F: FnOnce(State) -> Result<R>>(func: F) -> Result<R> {
+        let path = KUBIE_STATE_LOCK_PATH.display();
+
+        // Acquire the lock
+        let flock = File::create(lock_path())?;
```
Comment (TyBrown) [inline src/state.rs:61]: I suspect this is where the bug in #69 is coming from, since the directory that this gets created in is probably only created in `ioutil`. I'll add some `.context()` here and try a fresh install (no pre-existing directories) to see if that's correct.

Comment (sbstp) [reply src/state.rs:61]: Ah right of course. It's missing the `mkdir -p` with DirBuilder. I was trying to isolate the bug as well, I can try to reproduce this.

Comment (sbstp) [reply src/state.rs:61]: Yep that's it. I removed `~/.local/share/kubie` and I get the bug.

Comment (sbstp) [reply src/state.rs:61]: Are you working on a fix? If you're busy I can do it.
